[[JPADatastore]]
== JPA Datastore

The `holon-datastore-jpa` artifact is the main entry point to use the JPA `Datastore` API implementation.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jpa</groupId>
<artifactId>holon-datastore-jpa</artifactId>
<version>{revnumber}</version>
----

The link:{apidir}/com/holonplatform/datastore/jpa/JpaDatastore.html[JpaDatastore^] interface represents the *JPA Datastore* API implementation, extending the core `Datastore` API.

The `JpaDatastore` API, besides the standard `Datastore` API operations, provides methods to:

* Create and configure a `JpaDatastore` API instance, using the provided _builder_.
* Directly working with `JpaDatastore` managed _EntityManagers_, with a consistent and integrated `EntityManager` instance and related _persistence context_ lifecycle management. See <<JpaDatastoreAPI>>.

IMPORTANT: If you want to reach the goal of a *_complete abstraction_* from the persistence store technology and the persistence model, the core `Datastore` API interface should be used instead of the specific `JpaDatastore` API by your application code. This way, the concrete `Datastore` API implementation may be replaced by a different one at any time, without any change to the codebase.

[[JPADatastoreSetup]]
=== Setup and configuration

To create a *JPA Datastore* instance, the `builder()` static method of the `JpaDatastore` API can be used to obtain the JPA Datastore _builder_ API. 

The JPA Datastore builder provides a `JpaDatastore` instance:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jdbc/examples/ExampleJpaDatastoreConfiguration.java[tag=builder1,indent=0]
----
<1> Obtain the JPA `Datastore` builder to configure and create a new JPA Datastore instance

But, as stated in the previous section, to reach the goal of a *complete abstraction* from the persistence store technology and the persistence model, the core `Datastore` API interface should be used by your application code, instead of the specific `JpaDatastore` API.

So you can simply obtain the JPA Datastore implementation as a core `Datastore` API implementation:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jdbc/examples/ExampleJpaDatastoreConfiguration.java[tag=builder2,indent=0]
----
<1> Obtain the JPA Datastore builder to configure and create a new JPA Datastore instance and expose it as core `Datastore` API type 

==== Common Datastore configuration options

The JPA Datastore builder API extends the core `Datastore` builder API, which provides common Datastore configuration settings as listed below.

|===
|Builder method |Arguments |Description

|`dataContextId`
|The _data context id_ `String` value
|Set the _data context id_ to which the Datastore is bound. Can be used, for example, to declare configuration properties for multiple Datastore instances. See the link:holon-core#DatastoreDataContextId[Multiple Datastores configuration^] documentation section.

|`traceEnabled`
|`true` or `false`
|Whether to enable Datastore operations _tracing_. When enabled, the JPA Datastore will log any JPQL operation performed using the Datastore API.

|`configuration`
|A `DatastoreConfigProperties` instance
|Set the `DatastoreConfigProperties` type configuration property set instance to use in order to read the Datastore configuration properties. See the link:holon-core#DatastoreConfiguration[Datastore configuration^] documentation section for details. This configuration properties can be used as an alternative for the programmatic configuration performed with the previous builder methods. 
|===

Example of base JPA Datastore configuration:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jdbc/examples/ExampleJpaDatastoreConfiguration.java[tag=setup1,indent=0]
----
<1> Set a _data context id_ for the Datastore
<2> Activate operations _tracing_ in log

The configuration properties can also be provided through an external configuration property source, using the properties provided by the link:{coreapidir}/com/holonplatform/core/datastore/DatastoreConfigProperties.html[DatastoreConfigProperties^] property set.

For example, supposing to have a properties file named `datastore.properties` like this:

[source, text]
----
holon.datastore.trace=true
----

We can use it as configuration property source to enable the Datastore _tracing_ mode:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jdbc/examples/ExampleJpaDatastoreConfiguration.java[tag=setup2,indent=0]
----
<1> Use the `datastore.properties` file as configuration property source

==== `EntityManagerFactory` configuration

The JPA Datastore implementation relies on the standard JPA `EntityManagerFactory` API to obtain and manage the `EntityManager` instances to be used to perform the Datastore operations.

The `EntityManagerFactory` reference is the only *required* JPA Datastore configuration attribute and can be provided using the JPA `Datastore` _builder_ API.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jdbc/examples/ExampleJpaDatastoreConfiguration.java[tag=setup3,indent=0]
----
<1> Set the `EntityManagerFactory` instance to use


[[ORMPlatform]]
==== ORM platform configuration

For some internal operations, the JPA Datastore needs to know the _ORM platform_ which manages the concrete `EntityManagerFactory` (and accorrdingly the `EntityManager`) instances (for example _Hibernate_, _Eclipselink_ and so on). The _ORM platform_ is used, for example, to auto-detect the <<Dialect,ORM dialect>> to use if not directly specified at JPA Datastore configuration time.

The _ORM platform_ can be explicitly specified using the JPA Datastore `platform` builder method, using the link:{apidir}/com/holonplatform/jpa/ORMPlatform.html[ORMPlatform^] enumeration.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jdbc/examples/ExampleJpaDatastoreConfiguration.java[tag=setup5,indent=0]
----
<1> Set `Hibernate` as ORM platform

*ORM platform auto detection:*

When the _ORM platform_ is not explicitly specified, the JPA Datastore will *auto-detect* it using the configured `EntityManagerFactory`. 

[[Dialect]]
==== ORM Dialect configuration

To ensure operations consistency and efficiency, the JPA Datastore uses the link:{apidir}/com/holonplatform/jpa/dialect/ORMDialect.html[ORMDialect^] API abstraction in order to resolve each ORM platform specificity and JPQL language difference.

Normally, the `ORMDialect` implementation to use is *auto-detected* by the JPA Datastore, relying on the _ORM platform_ to which the `EntityManagerFactory` instance is bound, as described in the previous section.

The `ORMDialect` implementation to use can be also explicitly configured using the JPA Datastore builder. This can be done in two ways:

*1. `ORMDialect` configuration using the JPA Datastore builder:*

The ORM dialect to use can be directly configured using the JPA Datastore builder, either using the `dialect(ORMDialect dialect)` or the `dialect(String dialectClassName)` method.

The `ORMDialect` API provides a static methods to obtain the ORM dialect for a specific ORM platform or to directly obtain a specific dialect implementation within the available ones. 

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jdbc/examples/ExampleJpaDatastoreConfiguration.java[tag=setup6,indent=0]
----
<1> Configure the ORM dialect using a specific dialect implementation
<2> Configure the ORM dialect using the dialect class name

*1. `ORMDialect` configuration using a configuration property:*

The ORM dialect to use can be also configured using the default `holon.datastore.dialect` Datastore configuration property, available from the link:{coreapidir}/com/holonplatform/core/datastore/DatastoreConfigProperties.html[DatastoreConfigProperties^] property set.

The *fully qualified dialect class name* must be provided as property value.

For example, supposing to have a properties file named `datastore.properties` like this:

[source, text]
----
holon.datastore.dialect=com.holonplatform.datastore.jpa.dialect.HibernateDialect
holon.datastore.trace=true
----

We can use it as configuration property source to configure the JPA Datastore dialect:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jdbc/examples/ExampleJpaDatastoreConfiguration.java[tag=setup7,indent=0]
----
<1> Use the `datastore.properties` file as configuration property source

[[BuiltinORMDialects]]
==== Builtin ORM dialects

The Holon JPA Datastore module provides a set of builtin ORM dialects for the most common ORM platforms. The currently available ORM dialect implementations are:

|===
|ORM platform |Dialect class

|Hibernate
|link:{apidir}/com/holonplatform/datastore/jpa/dialect/HibernateDialect.html[HibernateDialect^]

|Eclipselink
|link:{apidir}/com/holonplatform/datastore/jpa/dialect/EclipselinkDialect.html[EclipselinkDialect^]

|Apache OpenJPA
|link:{apidir}/com/holonplatform/datastore/jpa/dialect/OpenJPADialect.html[OpenJPADialect^]

|Datanucleus
|link:{apidir}/com/holonplatform/datastore/jpa/dialect/DatanucleusDialect.html[DatanucleusDialect^]
|===

==== Auto-flush mode

The JPA `Datastore` API can be configured to automatically _flush_ the persistence context into the concrete persistence source when a data management operation of the `Datastore` API (such as _save_ or _delete_) is performed.

When the auto-flush mode is enabled, the `EntityManager.flush()` operation is invoked just after the `Datastore` API operation execution, forcing the persistence context synchronization to the underlying database.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jdbc/examples/ExampleJpaDatastoreConfiguration.java[tag=setup4,indent=0]
----
<1> Enable the auto-flush mode for the JPA `Datastore` API instance

=== Data targets and paths

The JPA `Datastore` relies on the following conventions regarding *DataTarget*s and *Path*s:

* The *DataTarget* _name_ is interpreted as the JPA _entity_ name (i.e. the simple Entity class name or the name specified using the `name` attribute of the `javax.persistence.Entity` annotation)
* The *Path* _name_ is interpreted as a JPA _entity_ attribute name, supporting nested classes through the conventional _dot_ notation (e.g. `address.city`)

TIP: See the core link:holon-core.html#Datastore[Datastore] documentation for more informations about *DataTarget*s and *Path*s, and about the use of extension hooks such as *DataTargetResolver* for target names resolution.

=== JpaTarget

The link:{apidir}/com/holonplatform/datastore/jpa/JpaTarget.html[JpaTarget^] interface can be used to define a *DataTarget* using a JPA _entity_ class rather than an entity name. The entity name used in persistence operations will be the provided entity class simple name or the name specified using the `name` attribute of the `javax.persistence.Entity` annotation, if available.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastore.java[tag=jpatarget,indent=0]
----
<1> Create a `DataTarget` bound to given `Test` JPA entity class using the `JpaTarget` interface

=== JPA Write options

The additional `WriteOption` link:{apidir}/com/holonplatform/datastore/jpa/JpaWriteOption.html#FLUSH[JpaWriteOption.FLUSH^] is supported by the JPA Datastore, and can be used to synchronize the persistence context to the underlying database after a data manipulation operation, automatically calling the `EntityManager.flush()` method.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastore.java[tag=flush,indent=0]
----

[[Relational-expressions]]
=== Relational expressions

As a _relational_ Datastore, the JPA Datastore supports core relational expressions for data access and manipulation:

*1. Sub-query:*

The link:{apidir}/com/holonplatform/core/datastore/relational/SubQuery.html[SubQuery^] interface can be used to represent a _sub-query_,  which can be used in a query definition to express query restrictions (filters) that involve a sub-query as filter operand.

See the link:holon-core.html#subquery[Sub query documentation] for further information and code examples.

*2. Alias and Joins:*

The link:{apidir}/com/holonplatform/core/datastore/relational/RelationalTarget.html[RelationalTarget^] interface can be used to express *alias* and *joins* for a `DataTarget`.

See the link:holon-core.html#joins[Alias and Joins documentation] for further information and code examples.

=== Auto-generated ids

The JPA datastore supports the retrieving of auto-generated id column values, if supported by the underlying JDBC driver and ORM platform.

The auto-generated id values can be obtained from the `OperationResult` object, returned by Datastore data manipulation operations, through the `getInsertedKeys()` method.

The default *BRING_BACK_GENERATED_IDS* `WriteOption` can be provided to Datastore data manipulation method to bring back any auto-generated id value into the `PropertyBox` which was subject of the operation, if a corresponding `Property` (using the property name) is available in the box property set.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastore.java[tag=ids,indent=0]
----
<1> The `id` column is supposed to be auto-generated by the ORM/database
<2> Create the `PropertyBox` to insert, not providing the `id` value
<3> Execute the insert operation using the *BRING_BACK_GENERATED_IDS* write option and the *FLUSH* JPA write option to ensure the id auto-generation is triggered
<4> The `ID` property of the inserted PropertyBox is updated with the auto-generated value

=== Extensions

=== Expression resolvers

The JPA Datastore supports `ExpressionResolver` automatic registration using the link:{apidir}/com/holonplatform/datastore/jpa/config/JpaDatastoreExpressionResolver.html[JpaDatastoreExpressionResolver^] base type and default _Java service extensions_.

To automatically register an `ExpressionResolver` this way, a class implementing `JpaDatastoreExpressionResolver` has to be created and its qualified full name must be specified in a file named `com.holonplatform.datastore.jpa.config.JpaDatastoreExpressionResolver` placed in a `META-INF/services` folder in classpath.

[[CommodityFactories]]
=== Commodity factories

The JPA Datastore supports `DatastoreCommodityFactory` automatic registration using the link:{apidir}/com/holonplatform/datastore/jpa/config/JpaDatastoreCommodityFactory.html[JpaDatastoreCommodityFactory^] base type and default _Java service extensions_.

To automatically register an `DatastoreCommodityFactory` this way, a class implementing `JpaDatastoreCommodityFactory` has to be created and its qualified full name must be specified in a file named `com.holonplatform.datastore.jpa.config.JpaDatastoreCommodityFactory` placed in a `META-INF/services` folder in classpath.

The link:{apidir}/com/holonplatform/datastore/jpa/config/JpaDatastoreCommodityContext.html[JpaDatastoreCommodityContext^] interface represents the JPA Datastore specific commodity context and it is provided at commodity creation time to the factories.

The context extends the `JpaDatastore` interface itself and provides the following additional resources:

* The `EntityManagerFactory` bound the JPA Datastore;
* A `getEntityManager()` method to obtain a `EntityManager` instance;
* The `ORMPlatform` used by the JPA Datastore, if available;
* Whether the Datastore _auto-flush_ mode is enabled.
* Whether the Datastore _trace_ mode is enabled.
