[[JPADatastoreSpring]]
== Spring ecosystem integration

The `holon-datastore-jpa-spring` artifact provides integration with the https://spring.io[Spring^] framework for the JPA `Datastore` API.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jpa</groupId>
<artifactId>holon-datastore-jpa-spring</artifactId>
<version>{revnumber}</version>
----

=== Integration with the Spring JPA infrastructure

When a JPA `Datastore` API is configured as a Spring bean using the facilities described in this documentation section, a consistent integration with the Spring JPA infrastructure is automatically provided.

In particular, the `EntityManager` instance used for the JPA `Datastore` API operations is obtained as a Spring *transactional `EntityManager` proxy*, using the `EntityManagerFactory` configured for the JPA `Datastore` implementation.

This allows to seamlessy integrate with the Spring transaction synchronization architecture, since the _shared_ `EntityManager` proxy provides the following behavior: it will delegate all calls to the current transactional `EntityManager`, if any; otherwise it will fall back to a newly created `EntityManager` per operation. 

This way, the JPA `Datastore` API can be seamlessly used along with the Spring transactions management conventions, for example when using a Spring `PlatformTransactionManager` or the `@Transactional` annotation.

[[EnableJpaDatastore]]
=== JPA Datastore configuration

The link:{apidir}/com/holonplatform/datastore/jpa/spring/EnableJpaDatastore.html[EnableJpaDatastore^] 
annotation can be used on Spring configuration classes to enable automatic JPA `Datastore` beans configuration.

NOTE: By default, the JPA Datastore bean name configured with the `@EnableJpaDatastore` annotation will be `jpaDatastore`.

==== EntityManagerFactory

The `EntityManagerFactory` bean to be used to configure the JPA Datastore API is obtained as follows:

* If the `entityManagerFactoryReference` attribute of the `@EnableJpaDatastore` annotation is setted, the provided *bean definition name* will be used as the `EntityManagerFactory` bean definition name to use.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring1.java[tag=config,indent=0]
----
<1> Provide the `EntityManagerFactory` bean definition name to use with the JPA Datastore
<2> The JPA Datastore is configured and made available, for example, using dependency injection

* Otherwise, the *default* `entityManagerFactory` bean definition name will be used to lookup for the `EntityManagerFactory` bean to use.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring2.java[tag=config,indent=0]
----
<1> The default `entityManagerFactory` bean definition name is used for the `EntityManagerFactory` bean definition
<2> The JPA Datastore is configured and made available, for example, using dependency injection

If a `EntityManagerFactory` bean definition whith the required name is not present in Spring context, an initialization error is thrown.

NOTE: See the <<EnableJpa>> section to learn how to auto-configure a complete JPA bean stack in the Spring context. 

==== Multiple JPA Datastores configuration

When more than one JPA Datastore bean has to be configured using the `@EnableJpaDatastore` annotation, the `dataContextId` attribute can be used to assign a different *data context id* to each JPA Datastore bean definition, in order to:

* Provide different sets of configuration properties using the same Spring environment.

* Provide a default _name pattern matching strategy_ with the `EntityManagerFactory` bean definition to use for each JPA Datastore to configure: if not directly specified with the `entityManagerFactoryReference` attribute, the `EntityManagerFactory` bean definition to use for each JPA Datastore will be detected in Spring context using the bean name pattern: `entityManagerFactory_{datacontextid}` where `{datacontextid}` is equal to the `dataContextId` attribute of the `@EnableJpaDatastore` annotation.

When a _data context id_ is defined, a Spring *qualifier* named the same as the _data context id_ will be associated to the generated JPA `Datastore` bean definitions, and such qualifier can be later used to obtain the right `Datastore` instance through dependency injection. 

Furthermore, the JPA Datastore bean definitions will be named using the _data context id_ as suffix, according to the name pattern: `jpaDatastore_{datacontextid}`.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring3.java[tag=config,indent=0]
----
<1> Configure the first JPA Datastore using `one` as _data context id_: by default the bean named `entityManagerFactory_one` will be used as `EntityManagerFactory`
<2> Configure the first JPA Datastore using `two` as _data context id_: by default the bean named `entityManagerFactory_two` will be used as `EntityManagerFactory`
<3> A specific `Datastore` type bean reference can be obtained using the _data context id_ as *qualifier*

==== Auto-flush mode

The JPA `Datastore` <<AutoFlush>> can be configured using the `autoFlush` attribute of the `@EnableJpaDatastore` annotation.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring6.java[tag=config,indent=0]
----
<1> Enable the JPA `Datastore` auto-flush mode

[[TransactionalJPADatastoreOperations]]
==== Transactional JPA Datastore operations

The `transactional` attribute of the `@EnableJpaDatastore` annotation can be used to control the _transactional_ configuration of a set of the `Datastore` API operations.

When setted to `true`, the Spring `@Transactional` annotation behavior is automatically added to the following `Datastore` API operation methods:

* `refresh`
* `insert`
* `update`
* `save`
* `delete`

The default `REQUIRED` _propagation_ behavior is used, thus allowing the method calls to participate in an existing transaction or to be executed in a new one when the Spring transactions infrastructure is used.

NOTE: The `transactional` attribute is *`true` by default*

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring7.java[tag=config,indent=0]
----
<1> Enables Spring's annotation-driven transaction management capability.
<2> The `insert` method is _transactional_ by default, so the `@Transactional` annotation is not explicitly required here

The `transactional` attribute can be used to disable this default behavior:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring8.java[tag=config2,indent=0]
----

==== Primary mode

The `@EnableJpaDatastore` annotation provides a `primary()` attribute which can be used to control the _primary mode_ of the JPA `Datastore` bean registration.

If the _primary mode_ is set to `PrimaryMode.TRUE`, the `Datastore` bean created with the corresponding annotation will be marked as *primary* in the Spring application context, meaning that will be the one provided by Spring in case of multiple available candidates, when no specific bean name or qualifier is specified in the dependency injection declaration.

TIP: This behaviour is similar to the one obtained with the Spring `@Primary` annotation at bean definition time.

By default, the _primary mode_ is set to `PrimaryMode.AUTO`, meaning that the registred JPA Datastore bean will be marked as *primary* only when the `EntityManagerFactory` bean to which is bound is registered as primary candidate bean.

[[SpringJPADatastoreConfigurationProperties]]
==== JPA Datastore configuration properties

When a JPA Datastore bean is configured using the `@EnableJpaDatastore` annotation, the Spring environment is automatically used as configuration properties source.

This way, many Datastore configuration settings can be provided using a configuration property with the proper name and value.

The supported configuration properties are:

*1. The standard Datastore configuration properties*, avaible from the link:{coreapidir}/com/holonplatform/core/datastore/DatastoreConfigProperties.html[DatastoreConfigProperties^] property set (See link:holon-core#DatastoreConfiguration[Datastore configuration^]).

The configuration property prefix is `holon.datastore` and the following properties are available:

.Datastore configuration properties
|===
|Name |Type |Meaning

|_holon.datastore._ *trace*
|Boolean (`true` / `false`)
|Enable/disable Datastore operations _tracing_.

|_holon.datastore._ *dialect*
|String
|The fully qualified class name of the _ORM Dialect_ to use. See <<Dialect>>.
|===

*2. An additional set of properties*, provided by the link:{apidir}/com/holonplatform/jpa/spring/JpaDatastoreConfigProperties.html[JpaDatastoreConfigProperties^] property set, which can be used as an alternative for the `@EnableJpaDatastore` annotation attributes described in the previous sections.

.JPA Datastore configuration properties
|===
|Name |Type |Meaning

|_holon.datastore.jpa._ *primary*
|Boolean (`true` / `false`)
|Mark the JPA Datastore bean as _primary_ candidate for dependency injection when more than one definition is available. IF not setted to `true`, the *AUTO* strategy will be used: the JPA Datastore bean will be marked as primary only when the `EntityManagerFactory` bean to which is bound is registered as primary candidate bean.

|_holon.datastore.jpa._ *auto-flush*
|Boolean (`true` / `false`)
|Enable or disable the JPA Datastore auto-flush mode. See <<AutoFlush>>.

|_holon.datastore.jpa._ *transactional*
|Boolean (`true` / `false`)
|Whether to add the Spring `@Transactional` behavior to the suitable Datastore API methods. See <<TransactionalJPADatastoreOperations>>.
|===

Example of Datastore configuration properties:

[source, text]
----
holon.datastore.trace=true // <1>
holon.datastore.dialect=my.dialect.class.Name // <2>

holon.datastore.jpa.auto-flush=true // <3>
holon.datastore.jpa.transactional=false // <4>
----
<1> Enable tracing
<2> Set the ORM dialect class name
<3> Enable the auto-flush mode
<4> Disable the automatic _transactional_ behavior of the Datastore operations

==== Datastore extension and configuration using the Spring context

The JPA Datastore implementation supports the standard link:holon-core.html#SpringDatastoreConfiguration[Holon Platform Datastore Spring integration^] features for Datastore beans configuration and extension, which includes:

* Datastore *configuration post processing* using  link:{coreapidir}/com/holonplatform/spring/DatastorePostProcessor.html[DatastorePostProcessor^] type beans.

* Datastore *extension* through link:{coreapidir}/com/holonplatform/core/ExpressionResolver.html[ExpressionResolver^] registration using link:{coreapidir}/com/holonplatform/spring/DatastoreResolver.html[DatastoreResolver^] annotated beans.

* Datastore *commodity factory* registration using link:{coreapidir}/com/holonplatform/spring/DatastoreCommodityFactory.html[DatastoreCommodityFactory^] annotated beans.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring9.java[tag=config,indent=0]
----
<1> Automatically register a Datastore expression resolver using the `@DatastoreResolver` annotation
<2> Post process Datastore configuration using a `DatastorePostProcessor` type Spring bean
<3> Automatically register a Datastore commodity factory using the `@DatastoreCommodityFactory` annotation

[[EnableJpa]]
=== Full JPA auto-configuration

The link:{apidir}/com/holonplatform/datastore/jpa/spring/EnableJpa.html[EnableJpa^] 
annotation can be used on Spring configuration classes to setup a full JPA enviroment bean stack: 

* *DataSource:* If a `javax.sql.DataSource` type bean is not already registered in Spring context, a `DataSource` instance is created and configured using standard JDBC `DataSourceConfigProperties`;
* *EntityManagerFactory:* A `javax.persistence.EntityManagerFactory` bean is registered and configured, along with a suitable Spring `JpaVendorAdapter` instance for ORM configuration;
* *PlatformTransactionManager:* A `org.springframework.transaction.PlatformTransactionManager` bean is registered to be used within the Spring transaction infrastructure;
* *Datastore:* A `JpaDatastore` is configured and bound to the `EntityManagerFactory` of the JPA stack.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring.java[tag=jpa,indent=0]
----

==== `EnableJpa`: DataSource configuration

A `DataSource` type bean is automatically configured if:

* A `javax.sql.DataSource` type bean is not already registered in Spring context;
* The `dataSourceReference` attribute of the `EnableJpa` is not specified. If specified, it indicates the `DataSource` bean name to use, which must be available in Spring context.

In order to auto-configure the `DataSource` bean, a suitable set of configuration properties must be available in Spring environment (typically using one or more `PropertySource`).

See link:../../holon-jdbc/overview.html#DataSourceConfigProperties[DataSource configuration properties^] for details.

==== `EnableJpa`: EntityManagerFactory configuration

A Spring `LocalContainerEntityManagerFactoryBean` instance is used as `javax.persistence.EntityManagerFactory` implementation to ensure a full integration with Spring JPA architecture and provide functionalities such as automatic JPA persistence unit configuration without the need of a `persistence.xml` configuration file.

If a `persistence.xml` configuration file is not available, automatic persistence unit _entity_ classes configuration can be performed using either the annotation attribute:

* `entityPackages` : providing a list of package names to scan in order to map JPA _entity_ classes into the  `EntityManagerFactory`,

or the annotation attribute:

* `entityPackageClasses` : providing a list of classes from which to obtain the package names to scan in order to map JPA _entity_ classes into the `EntityManagerFactory`. Represents a type-safe alternative to `entityPackages` attribute.

Two more annotation attributes are available for persistence unit configuration:

* `validationMode` : Specify the JPA 2.0 validation mode for the persistence unit;
* `sharedCacheMode` : Specify the JPA 2.0 shared cache mode for the persistence unit.

See the JPA documentation for further details about persistence unit configuration.

==== `EnableJpa`: Persistence provider (ORM) configuration

The JPA Persistence provider (ORM) to use is auto-detected from classpath and a suitable Spring `JpaVendorAdapter` instance is configured and bound to the `EntityManagerFactory`.

See link:{apidir}/com/holonplatform/datastore/jpa/ORMPlatform.html[ORMPlatform^] enumeration for a list of supported persistence provider implementations.

If more than one persistence provider implementation is present in classpath (or to explicitly specify a persistence provider implementation to use, anyway) the `orm` configuration property can be used. See <<JPA configuration properties>> for details.

==== `EnableJpa`: Transaction manager configuration

A Spring JPA `PlatformTransactionManager` is auto-configured and bound to the 
`EntityManagerFactory` to enable Spring's transaction infrastructure support.

A set of attributes are made available by the `@EnableJpa` annotation to fine tune the transaction manager configuration: `transactionSynchronization`, `defaultTimeout`, `validateExistingTransaction`, `failEarlyOnGlobalRollbackOnly`, `rollbackOnCommitFailure`.

See link:{apidir}/com/holonplatform/datastore/jpa/spring/EnableJpa.html[EnableJpa^] Javadocs for informations about each of these configuration attributes.

==== `EnableJpa`: JPA Datastore configuration

By default, using the `EnableJpa` annotation a JPA Datastore is automatically created and configured suing the `EntityManagerFactory` of the JPA beans stack. The JPA Datastore instanc will be a <<SpringJpaDatastore>>, enabling all the Spring-related auto-configuration features described above.

To disable automatic JPA Datastore configuration, the `enableDatastore` annotation attribute can be used.

The `EnableJpa` annotation makes available two additional configuration attributes related to the JPA Datastore setup:

* `autoFlush` : to enable the JPA Datastore _auto flush_ mode. When auto-flush mode is enabled,
the `EntityManager.flush()` method is invoked after each Datastore data manipulation operation to ensure the underlying database synchronization.

* `transactionalDatastore` : to add _transactional_ behaviour to
suitable Datastore methods, i.e. to automatically create or partecipate in a transaction when methods are invoked.

==== Using _data context id_ for multiple data sources

When a _data context id_ is specified through the `dataContextId` annotation attribute, all the JPA stack beans auto-configured with the `EnableJpa` annotation are bound to the specified _data context id_ name, allowing the support for multiple data sources and persistence units.

When a _data context id_ is specified:

* Any configuration property (for `DataSource` or JPA beans configuration) must be provided using the _data context id_ as prefix. For example, if the _data context id_ is named `test`, the JDBC DataSource url must be specified the following way: `holon.datasource.test.url=...` and so on;

* The _data context id_ will be used as persistence unit name;

* Each of the auto-configured JPA stack bean will be _qualified_ using the _data context id_ name, to allow dependency injection using a Spring `Qualifier`.

In case of multiple data context ids, the `primary()` attribute of the `EnableJpa` annotation can be used to mark one the JPA beans stack as primary candidate for dependency injection when a qualifier is not specified.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring.java[tag=multi,indent=0]
----

[[JPA configuration properties]]
=== JPA configuration properties

link:{apidir}/com/holonplatform/jpa/spring/JpaConfigProperties.html[JpaConfigProperties^] interface provides a set of configuration properties to be used with JPA stack beans auto-configuration. It extends a default `ConfigPropertySet` bound to the property name prefix *holon.jpa*.

The available configuration properties are listed below:

.JPA configuration properties
|===
|Name |Type |Meaning

|_holon.jpa._ *orm*
|link:{apidir}/com/holonplatform/datastore/jpa/ORMPlatform.html[ORMPlatform^] enumeration
|ORM platform to use as persistence provider.

|_holon.jpa._ *dialect*
|String
|ORM dialect class name to use, if supported by the ORM platform.

| _holon.jpa._ *database*
|`com.holonplatform.jdbc.DatabasePlatform` enumeration
|Database platform to which the `DataSource` is connected (auto-detected by default).

|_holon.jpa._ *generate-ddl*
|Boolean (true/false)
|Whether to initialize the database schema on startup.

|_holon.jpa._ *show-sql*
|Boolean (true/false)
|Whether to instruct JPA ORM engine to show executed SQL statements, if supported by ORM platform.
|===

The `JpaConfigProperties` can be loaded from a number a sources using the default `ConfigPropertySet` builder interface.

Using the Spring integration, all `Environment` registered PropertySources will be enabled as a `JpaConfigProperties` source.

== Spring Boot integration

The `holon-datastore-jpa-spring-boot` artifact provides integration with https://projects.spring.io/spring-boot[Spring Boot^] for JPA stack and Datastore auto-configuration.

To enable Spring Boot auto-configuration the following artifact must be included in your project dependencies:

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jpa</groupId>
<artifactId>holon-datastore-jpa-spring-boot</artifactId>
<version>{revnumber}</version>
----

=== JPA Datastore auto-configuration

The JPA datastore is auto-configured only when:

* A `JpaDatastore` type bean is not already registered in Spring context
* A valid `EntityManagerFactory` type bean is available in Spring context

The JPA Datastore auto-configuration behaviour is the same of the one adopted by the `EnableJpaDatastore` annotation. See <<EnableJpaDatastore>> for details.

To disable this auto-configuration feature the `JpaDatastoreAutoConfiguration` class can be excluded:

[source, java]
----
@EnableAutoConfiguration(exclude={JpaDatastoreAutoConfiguration.class})
----

=== Full JPA stack auto-configuration

A full JPA beans stack is auto-configured only when:

* An `EntityManagerFactory` type bean is not already registered in Spring context.

The JPA stack auto-configuration behaviour is the same of the one adopted by the `EnableJpa` annotation. See <<EnableJpa>> for details.

To disable this auto-configuration feature the `JpaAutoConfiguration` class can be excluded:

[source, java]
----
@EnableAutoConfiguration(exclude={JpaAutoConfiguration.class})
----

==== JPA entities scan

When the full JPA stack auto-configuration is enabled, the link:{apidir}/com/holonplatform/jpa/spring/boot/JpaEntityScan.html[JpaEntityScan^] repeatable annotation can be used on Spring configuration classes to specify the base packages to scan for JPA entity classes.

=== Spring Boot starters

The following _starter_ artifacts are available to provide a quick project configuration setup using Maven dependency system:

*1.* *JPA Datastore starter using Hibernate* provides the dependencies to the Holon JPA Datastore Spring Boot integration artifacts, in addition to default Holon _core_ Spring Boot starters (see the documentation for further information) and base Spring Boot starter (`spring-boot-starter`). Futhermore, this starter provides the *Hibernate ORM* and the *HikariCP* DataSource dependencies.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jpa</groupId>
<artifactId>holon-starter-jpa-hibernate</artifactId>
<version>{revnumber}</version>
----

*2.* *JPA Datastore starter using Eclipselink* provides the dependencies to the Holon JPA Datastore Spring Boot integration artifacts, in addition to default Holon _core_ Spring Boot starters (see the documentation for further information) and base Spring Boot starter (`spring-boot-starter`). Futhermore, this starter provides the *Eclipselink ORM* and the *HikariCP* DataSource dependencies.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jpa</groupId>
<artifactId>holon-starter-jpa-eclipselink</artifactId>
<version>{revnumber}</version>
----
