[[JPADatastoreSpring]]
== Spring ecosystem integration

The `holon-datastore-jpa-spring` artifact provides integration with the https://spring.io[Spring^] framework for the JPA `Datastore` API.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jpa</groupId>
<artifactId>holon-datastore-jpa-spring</artifactId>
<version>{revnumber}</version>
----

[[SpringJPAIntegration]]
=== Integration with the Spring JPA infrastructure

When a JPA `Datastore` API is configured as a Spring bean using the facilities described in this documentation section, a consistent integration with the Spring JPA infrastructure is automatically provided.

In particular, the `EntityManager` instance used for the JPA `Datastore` API operations is obtained as a Spring *transactional `EntityManager` proxy*, using the `EntityManagerFactory` configured for the JPA `Datastore` implementation.

This allows to seamlessy integrate with the Spring transaction synchronization architecture, since the _shared_ `EntityManager` proxy provides the following behavior: it will delegate all calls to the current transactional `EntityManager`, if any; otherwise it will fall back to a newly created `EntityManager` per operation. 

This way, the JPA `Datastore` API can be seamlessly used along with the Spring transactions management conventions, for example when using a Spring `PlatformTransactionManager` or the `@Transactional` annotation.

[[EnableJpaDatastore]]
=== JPA Datastore configuration

The link:{apidir}/com/holonplatform/datastore/jpa/spring/EnableJpaDatastore.html[EnableJpaDatastore^] 
annotation can be used on Spring configuration classes to enable automatic JPA `Datastore` beans configuration.

NOTE: By default, the JPA Datastore bean name configured with the `@EnableJpaDatastore` annotation will be `jpaDatastore`.

==== EntityManagerFactory

The `EntityManagerFactory` bean to be used to configure the JPA Datastore API is obtained as follows:

* If the `entityManagerFactoryReference` attribute of the `@EnableJpaDatastore` annotation is setted, the provided *bean definition name* will be used as the `EntityManagerFactory` bean definition name to use.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring1.java[tag=config,indent=0]
----
<1> Provide the `EntityManagerFactory` bean definition name to use with the JPA Datastore
<2> The JPA Datastore is configured and made available, for example, using dependency injection

* Otherwise, the *default* `entityManagerFactory` bean definition name will be used to lookup for the `EntityManagerFactory` bean to use.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring2.java[tag=config,indent=0]
----
<1> The default `entityManagerFactory` bean definition name is used for the `EntityManagerFactory` bean definition
<2> The JPA Datastore is configured and made available, for example, using dependency injection

If a `EntityManagerFactory` bean definition whith the required name is not present in Spring context, an initialization error is thrown.

NOTE: See the <<EnableJpa>> section to learn how to auto-configure a complete JPA bean stack in the Spring context. 

==== Multiple JPA Datastores configuration

When more than one JPA Datastore bean has to be configured using the `@EnableJpaDatastore` annotation, the `dataContextId` attribute can be used to assign a different *data context id* to each JPA Datastore bean definition, in order to:

* Provide different sets of configuration properties using the same Spring environment.

* Provide a default _name pattern matching strategy_ with the `EntityManagerFactory` bean definition to use for each JPA Datastore to configure: if not directly specified with the `entityManagerFactoryReference` attribute, the `EntityManagerFactory` bean definition to use for each JPA Datastore will be detected in Spring context using the bean name pattern: `entityManagerFactory_{datacontextid}` where `{datacontextid}` is equal to the `dataContextId` attribute of the `@EnableJpaDatastore` annotation.

When a _data context id_ is defined, a Spring *qualifier* named the same as the _data context id_ will be associated to the generated JPA `Datastore` bean definitions, and such qualifier can be later used to obtain the right `Datastore` instance through dependency injection. 

Furthermore, the JPA Datastore bean definitions will be named using the _data context id_ as suffix, according to the name pattern: `jpaDatastore_{datacontextid}`.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring3.java[tag=config,indent=0]
----
<1> Configure the first JPA Datastore using `one` as _data context id_: by default the bean named `entityManagerFactory_one` will be used as `EntityManagerFactory`
<2> Configure the first JPA Datastore using `two` as _data context id_: by default the bean named `entityManagerFactory_two` will be used as `EntityManagerFactory`
<3> A specific `Datastore` type bean reference can be obtained using the _data context id_ as *qualifier*

==== Auto-flush mode

The JPA `Datastore` <<AutoFlush>> can be configured using the `autoFlush` attribute of the `@EnableJpaDatastore` annotation.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring6.java[tag=config,indent=0]
----
<1> Enable the JPA `Datastore` auto-flush mode

[[TransactionalJPADatastoreOperations]]
==== Transactional JPA Datastore operations

The `transactional` attribute of the `@EnableJpaDatastore` annotation can be used to control the _transactional_ configuration of a set of the `Datastore` API operations.

When setted to `true`, the Spring `@Transactional` annotation behavior is automatically added to the following `Datastore` API operation methods:

* `refresh`
* `insert`
* `update`
* `save`
* `delete`

The default `REQUIRED` _propagation_ behavior is used, thus allowing the method calls to participate in an existing transaction or to be executed in a new one when the Spring transactions infrastructure is used.

NOTE: The `transactional` attribute is *`true` by default*

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring7.java[tag=config,indent=0]
----
<1> Enables Spring's annotation-driven transaction management capability.
<2> The `insert` method is _transactional_ by default, so the `@Transactional` annotation is not explicitly required here

The `transactional` attribute can be used to disable this default behavior:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring8.java[tag=config2,indent=0]
----

==== Primary mode

The `@EnableJpaDatastore` annotation provides a `primary()` attribute which can be used to control the _primary mode_ of the JPA `Datastore` bean registration.

If the _primary mode_ is set to `PrimaryMode.TRUE`, the `Datastore` bean created with the corresponding annotation will be marked as *primary* in the Spring application context, meaning that will be the one provided by Spring in case of multiple available candidates, when no specific bean name or qualifier is specified in the dependency injection declaration.

TIP: This behaviour is similar to the one obtained with the Spring `@Primary` annotation at bean definition time.

By default, the _primary mode_ is set to `PrimaryMode.AUTO`, meaning that the registred JPA Datastore bean will be marked as *primary* only when the `EntityManagerFactory` bean to which is bound is registered as primary candidate bean.

[[SpringJPADatastoreConfigurationProperties]]
==== JPA Datastore configuration properties

When a JPA Datastore bean is configured using the `@EnableJpaDatastore` annotation, the Spring environment is automatically used as configuration properties source.

This way, many Datastore configuration settings can be provided using a configuration property with the proper name and value.

The supported configuration properties are:

*1. The standard Datastore configuration properties*, avaible from the link:{coreapidir}/com/holonplatform/core/datastore/DatastoreConfigProperties.html[DatastoreConfigProperties^] property set (See link:holon-core#DatastoreConfiguration[Datastore configuration^]).

The configuration property prefix is `holon.datastore` and the following properties are available:

.Datastore configuration properties
|===
|Name |Type |Meaning

|_holon.datastore._ *trace*
|Boolean (`true` / `false`)
|Enable/disable Datastore operations _tracing_.

|_holon.datastore._ *dialect*
|String
|The fully qualified class name of the _ORM Dialect_ to use. See <<Dialect>>.
|===

*2. An additional set of properties*, provided by the link:{apidir}/com/holonplatform/jpa/spring/JpaDatastoreConfigProperties.html[JpaDatastoreConfigProperties^] property set, which can be used as an alternative for the `@EnableJpaDatastore` annotation attributes described in the previous sections.

.JPA Datastore configuration properties
|===
|Name |Type |Meaning

|_holon.datastore.jpa._ *primary*
|Boolean (`true` / `false`)
|Mark the JPA Datastore bean as _primary_ candidate for dependency injection when more than one definition is available. IF not setted to `true`, the *AUTO* strategy will be used: the JPA Datastore bean will be marked as primary only when the `EntityManagerFactory` bean to which is bound is registered as primary candidate bean.

|_holon.datastore.jpa._ *auto-flush*
|Boolean (`true` / `false`)
|Enable or disable the JPA Datastore auto-flush mode. See <<AutoFlush>>.

|_holon.datastore.jpa._ *transactional*
|Boolean (`true` / `false`)
|Whether to add the Spring `@Transactional` behavior to the suitable Datastore API methods. See <<TransactionalJPADatastoreOperations>>.
|===

Example of Datastore configuration properties:

[source, text]
----
holon.datastore.trace=true // <1>
holon.datastore.dialect=my.dialect.class.Name // <2>

holon.datastore.jpa.auto-flush=true // <3>
holon.datastore.jpa.transactional=false // <4>
----
<1> Enable tracing
<2> Set the ORM dialect class name
<3> Enable the auto-flush mode
<4> Disable the automatic _transactional_ behavior of the Datastore operations

[[SpringDatastoreExtensionConfiguration]]
==== Datastore extension and configuration using the Spring context

The JPA Datastore implementation supports the standard link:holon-core.html#SpringDatastoreConfiguration[Holon Platform Datastore Spring integration^] features for Datastore beans configuration and extension, which includes:

* Datastore *configuration post processing* using  link:{coreapidir}/com/holonplatform/spring/DatastorePostProcessor.html[DatastorePostProcessor^] type beans.

* Datastore *extension* through link:{coreapidir}/com/holonplatform/core/ExpressionResolver.html[ExpressionResolver^] registration using link:{coreapidir}/com/holonplatform/spring/DatastoreResolver.html[DatastoreResolver^] annotated beans.

* Datastore *commodity factory* registration using link:{coreapidir}/com/holonplatform/spring/DatastoreCommodityFactory.html[DatastoreCommodityFactory^] annotated beans.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring9.java[tag=config,indent=0]
----
<1> Automatically register a Datastore expression resolver using the `@DatastoreResolver` annotation
<2> Post process Datastore configuration using a `DatastorePostProcessor` type Spring bean
<3> Automatically register a Datastore commodity factory using the `@DatastoreCommodityFactory` annotation

[[EnableJpa]]
=== Full JPA bean stack auto-configuration

The link:{apidir}/com/holonplatform/datastore/jpa/spring/EnableJpa.html[EnableJpa^] 
annotation can be used on Spring configuration classes to setup a full JPA enviroment bean stack: 

* *DataSource:* If a `javax.sql.DataSource` type bean is not already registered in Spring context, a `DataSource` instance is created and configured using the link:holon-jdbc.html#DataSourceConfigProperties[Holon Platform DataSource configuration properties^]. See the link:holon-jdbc.html#DataSourceConfiguration[Holon Platform JDBC Module^] documentation for details.

* *EntityManagerFactory:* A JPA `javax.persistence.EntityManagerFactory` bean is registered and configured, along with a suitable Spring `JpaVendorAdapter` instance for ORM configuration. A default Spring `LocalContainerEntityManagerFactoryBean` is used as `EntityManagerFactory` factory bean.

* *PlatformTransactionManager:* A `org.springframework.transaction.PlatformTransactionManager` bean is registered to enable the Spring transactions management APIs and conventions;

* *Datastore:* A JPA `Datastore` is configured and bound to the `EntityManagerFactory` bean of the JPA stack.

In a typical scenario, to enable a full JPA stack in Spring context, the `@EnableJpa` annotation can be used as foolows:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring4.java[tag=config,indent=0]
----
<1> Specify the base package to use to auto-detect the JPA _entity_ definition classes to mapped into the `EntityManagerFactory` instance

The `DataSource` configuration properties in the example above are expected to be provided through the `jdbc.properties` file. For example:

[source, text]
----
holon.datasource.url=jdbc:h2:mem:test
holon.datasource.username=sa
----

See the next sections to learn about all the available configuration attributes to fine tune the JPA stack beans configuration.

==== `DataSource` configuration

A `DataSource` type bean is automatically configured if:

* A `javax.sql.DataSource` type bean is not already registered in the Spring context.
* The `dataSourceReference` attribute of the `@EnableJpa` annotation is not specified. If specified, it indicates the `DataSource` bean name to use, which must be available in the Spring context.

In order to auto-configure the `DataSource` bean, a suitable set of configuration properties must be available in the Spring Environment.

See the link:holon-jdbc.html#DataSourceConfigProperties[Holon Platform DataSource configuration properties^] section of the Holon Platform JDBC Module documentation for details.

==== `EntityManagerFactory` configuration

A Spring `LocalContainerEntityManagerFactoryBean` instance is used as `javax.persistence.EntityManagerFactory` implementation to ensure a full integration with Spring JPA architecture and provide functionalities such as automatic JPA persistence unit configuration without the need of a `persistence.xml` configuration file.

If a `persistence.xml` configuration file is not available, automatic persistence unit _entity_ classes configuration can be performed using one of the following `@EnableJpa` annotation attributes:

* `entityPackages` : providing a list of package names to scan in order to map JPA _entity_ classes into the  `EntityManagerFactory`,
* `entityPackageClasses` : providing a list of classes from which to obtain the package names to scan in order to map JPA _entity_ classes into the `EntityManagerFactory`. Represents a type-safe alternative to `entityPackages` attribute.

Two more annotation attributes are available for persistence unit configuration:

* `validationMode` : Specify the JPA 2.0 validation mode for the persistence unit;
* `sharedCacheMode` : Specify the JPA 2.0 shared cache mode for the persistence unit.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring10.java[tag=config,indent=0]
----

==== Persistence provider (ORM) configuration

By default, the JPA Persistence provider (ORM) to use is *auto-detected from classpath* and a suitable Spring `JpaVendorAdapter` instance is configured and bound to the `EntityManagerFactory` bean.

If more than one persistence provider implementation is present in classpath (or to explicitly specify a persistence provider implementation to use, anyway) the `orm` configuration property can be used. See <<JPAConfigurationProperties>> for details.

==== Transaction manager configuration

A Spring JPA `PlatformTransactionManager` is auto-configured and bound to the 
`EntityManagerFactory` bean to enable the Spring's transactions support.

A set of attributes are made available by the `@EnableJpa` annotation to fine tune the transaction manager configuration: 

|===
|Attribute name |Type |Meaning |Default

|`transactionSynchronization`
|int
|Set when the transaction manager should activate the thread-bound transaction synchronization support. 
|-1 (always)

|`defaultTimeout`
|int
|Specify the default timeout that the transaction manager should apply if there is no timeout specified at the transaction level, in seconds.
|-1 (`TransactionDefinition.TIMEOUT_DEFAULT`)

|`validateExistingTransaction`
|boolean
|Set whether existing transactions should be validated before participating in them.
|`false`

|`failEarlyOnGlobalRollbackOnly`
|boolean
|Set whether to fail early in case of the transaction being globally marked as rollback-only. 
|`false`

|`rollbackOnCommitFailure`
|boolean
|Set whether a _rollback_ should be performed on failure of the transaction manager _commit_ call. 
|`false`
|===

==== JPA Datastore configuration

By default, a JPA `Datastore` implementation is automatically configured using the `EntityManagerFactory` bean and made available as Spring bean. The JPA `Datastore` implementation is configured for a seamless integration with the Spring JPA infrastructure, as described in <<SpringJPAIntegration>>.

To disable automatic JPA Datastore configuration, the `enableDatastore` attribute of the `@EnableJpa` annotation can be used.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring11.java[tag=config,indent=0]
----
<1> Disable the JPA `Datastore` bean auto configuration

The `@EnableJpa` annotation makes available two additional configuration attributes related to the JPA `Datastore` implementation setup:

* `autoFlush` : whether to enable the JPA `Datastore` _auto flush_ mode. See <<AutoFlush>> for details.

* `transactionalDatastore` : whether to add _transactional_ behaviour to data manipulation `Datastore` API operations. See <<TransactionalJPADatastoreOperations>> for details.

[[JPAConfigurationProperties]]
==== JPA configuration properties

The link:{apidir}/com/holonplatform/jpa/spring/JpaConfigProperties.html[JpaConfigProperties^] interface provides a set of configuration properties to be used with JPA stack beans auto-configuration. It extends a default `ConfigPropertySet` bound to the property name prefix *holon.jpa*.

The available configuration properties are listed below:

.JPA configuration properties
|===
|Name |Type |Meaning

|_holon.jpa._ *orm*
|link:{apidir}/com/holonplatform/datastore/jpa/ORMPlatform.html[ORMPlatform^] enumeration
|ORM platform to use as persistence provider.

|_holon.jpa._ *dialect*
|String
|ORM dialect class name to use.

| _holon.jpa._ *database*
|`com.holonplatform.jdbc.DatabasePlatform` enumeration
|Database platform to which the `DataSource` is connected (auto-detected by default).

|_holon.jpa._ *generate-ddl*
|Boolean (true/false)
|Whether to initialize the database schema on startup.

|_holon.jpa._ *show-sql*
|Boolean (true/false)
|Whether to instruct JPA ORM engine to show executed SQL statements, if supported by the ORM platform.
|===

The `JpaConfigProperties` can be loaded from a number a sources using the default `ConfigPropertySet` builder interface.

Using the Spring integration, all `Environment` registered PropertySources will be enabled as a `JpaConfigProperties` source.

==== Multiple JPA bean stacks configuration

When more than one JPA stack has to be configured using the `@EnableJpa` annotation, the `dataContextId` attribute can be used to assign a different *data context id* to each JPA bean definitions stack, in order to:

* Provide different sets of configuration properties using the same Spring environment.

* Provide a default _name pattern strategy_ for the JPA beans stack using the bean name pattern: `beanDefinitionName_{datacontextid}` where `{datacontextid}` is equal to the `dataContextId` attribute of the `@EnableJpa` annotation.

When a _data context id_ is defined, a Spring *qualifier* named the same as the _data context id_ will be associated to each JPA bean definition, and such qualifier can be later used to obtain the right bean instance through dependency injection.

For example, given the following `jdbc.properties` configuration property source file:

[source, text]
----
holon.datasource.one.url=jdbc:h2:mem:testdbm1
holon.datasource.one.username=sa

holon.datasource.two.url=jdbc:h2:mem:testdbm2
holon.datasource.two.username=sa
----

To configure two JPA bean stacks, one bound to the `one` _data context id_ and the other to the `two` _data context id_, the `@EnableJpa` annotation can be used as follows:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring5.java[tag=config,indent=0]
----

[[ProgrammaticJPADatastoreConfiguration]]
==== Programmatic JPA Datastore bean configuration

When a JPA `Datastore` is not istantiated and configured in a Spring context using the `@EnableJpaDatastore` annotation, but rather providing the bean implementation programmatically (for example using the `JpaDatastore` builder API), the Spring integration features described in the previous sections must be explicitly enabled:

* To use the Spring managed `EntityManager` instances, the link:{apidir}/com/holonplatform/jpa/spring/SpringEntityManagerLifecycleHandler.html[SpringEntityManagerLifecycleHandler^] `EntityManager` lifecycle handler can be configured for the `JpaDatastore` bean.

* To enable the automatic Datastore bean configuration, as described in <<SpringDatastoreExtensionConfiguration>>, the `@EnableDatastoreConfiguration` annotation can be used on Spring configuration classes.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring12.java[tag=config,indent=0]
----
<1> Use the `@EnableDatastoreConfiguration` to automatically configure the `Datastore` with auto-detected `Datastore` configuration context beans
<2> Set a `SpringEntityManagerLifecycleHandler` instance as `Datastore` `EntityManager` lifecycle handler to use Spring managed `EntityManager` proxies

[[JPASpringBoot]]
== Spring Boot integration

The `holon-datastore-jpa-spring-boot` artifact provides integration with https://projects.spring.io/spring-boot[Spring Boot^] for JPA stack and JPA `Datastore` beans *auto-configuration*.

To enable Spring Boot JPA auto-configuration features, the following artifact must be included in your project dependencies:

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jpa</groupId>
<artifactId>holon-datastore-jpa-spring-boot</artifactId>
<version>{revnumber}</version>
----

[[JPADatastoreSpringBoot]]
=== JPA Datastore auto-configuration

A JPA `Datastore` bean is auto-configured only when:

* A `JpaDatastore` type bean is not already available from the Spring application context.
* A valid `EntityManagerFactory` type bean is available from the Spring application context.

The JPA `Datastore` auto-configuration strategy is the same adopted by the `@EnableJpaDatastore` annotation, including the Spring environment configuration properties support. See <<EnableJpaDatastore>> for details.

For example, given an `application.yml` configuration file as follows:

[source, yaml]
----
holon: 
  datastore:
    trace: true
----

The Holon platform Spring Boot auto-configuration classes will auto configure a JPA `Datastore` bean bound to the `EntityManagerFactory` bean (which must be available in the Spring application context), enabling operations _tracing_ according to the `holon.datastore.trace` property value.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpringBoot1.java[tag=config,indent=0]
----
<1> A JPA `Datastore` type bean is auto-configured ad available from the Spring context

To disable this auto-configuration feature the `JpaDatastoreAutoConfiguration` class can be excluded:

[source, java]
----
@EnableAutoConfiguration(exclude={JpaDatastoreAutoConfiguration.class})
----

[[JPAStackSpringBoot]]
=== Full JPA beans stack auto-configuration

When the `holon-datastore-jpa-spring-boot` artifact is available in classpath, a *full JPA beans stack* is auto-configured when an `EntityManagerFactory` type bean is not already registered in the Spring application context.

The JPA beans stack configuration strategy is the same of the one adopted by the `@EnableJpa` annotation, including the Spring environment configuration properties support. See <<EnableJpa>> for details.

For example, given an `application.yml` configuration file as follows:

[source, yaml]
----
spring:
  datasource:
    url: "jdbc:h2:mem:test"
    username: "sa"
    
holon: 
  datastore:
    trace: true
----

The Holon platform Spring Boot auto-configuration classes will auto configure a JPA beans stack using the `DataSource` auto-configured by the standard Spring Boot classes `spring.datasource.*` configuration properties. The Datastore operations _tracing_ is enabled according to the `holon.datastore.trace` property value.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpringBoot2.java[tag=config,indent=0]
----

The Holon Platform `DataSource` auto-configuration capabilities can also be used, replacing the `spring.datasource.*` configuration properties with the `holon.datasource.*` ones. For example:

[source, yaml]
----
holon:
  datasource:
    url: "jdbc:h2:mem:test"
    username: "sa"
 
  datastore:
    trace: true
----

To disable this auto-configuration feature the `JpaAutoConfiguration` class can be excluded:

[source, java]
----
@EnableAutoConfiguration(exclude={JpaAutoConfiguration.class})
----

=== Multiple JPA beans stack auto configuration

When the `DataSource` type beans are auto-configured using the Holon Platform JDBC Module features (see the link:holon-jdbc.html#JDBCSpringBoot[Holon Platform JDBC Module Spring Boot integration^] documentation section), the auto-configuration of multiple JPA bean stacks is available out-of-the-box.

The *_data context id_ convention* is used to provide multiple `DataSource` and JPA beans stack auto-configuration capabilities: when multiple `DataSource` type beans are registered, each of them bound to a _data context id_, the Spring Boot auto-configuration classes will provide to configure a JPA beans stack for each detected `DataSource` bean, binding the same _data context id_ to the JPA stack bean definitions.

According to the _data context id_ convention, each `DataSource` and JPA stack bean will be _qualified_ with the corresponding _data context id_, so that the specific bean instance can be later obtained using the _data context id_ as Spring bean *qualifier* name.

For example, given an `application.yml` configuration file as follows:

[source, yaml]
----
holon: 
  datasource:
    one:
      url: "jdbc:h2:mem:test1"
      username: "sa"
    two:
      url: "jdbc:h2:mem:test2"
      username: "sa"
----

The auto-configuration feature will configure two `DataSource` beans:

* One `DataSource` bean instance using the `one` _data context id_ configuration properties, qualified with the *one* qualifier.
* Another `DataSource` bean instance using the `two` _data context id_ configuration properties, qualified with the *two* qualifier.

And two corresponding JPA beans stacks:

* One backed by the `DataSource` bound to the `one` _data context id_, qualified with the *one* qualifier.
* Another backed by the `DataSource` bound to the `two` _data context id_, qualified with the *two* qualifier.

So, for example, the `DataSource` and JPA `Datastore` beans can be obtained as follows:

[source, java]
----
// 'one' data context id:
@Autowired @Qualifier("one")
DataSource dataSource1;
	
@Autowired @Qualifier("one")
Datastore datastore1;

// 'two' data context id:
@Autowired @Qualifier("two")
DataSource dataSource2;
	
@Autowired @Qualifier("two")
Datastore datastore2;
----

==== JPA entities scan

When more than one JPA beans stack is auto-configured, the link:{apidir}/com/holonplatform/jpa/spring/boot/JpaEntityScan.html[JpaEntityScan^] repeatable annotation can be used to provide the JPA _entity_ set to map to each auto-configured `EntityManagerFactory`, using the _data context id_ value to identify each `EntityManagerFactory` bean.

So, for example, given an `application.yml` configuration file as follows:

[source, yaml]
----
holon: 
  datasource:
    one:
      url: "jdbc:h2:mem:test1"
      username: "sa"
    two:
      url: "jdbc:h2:mem:test2"
      username: "sa"
----

Two `DataSource` beans and two JPA beans stacks will be auto-configured using the `one` and `two` data context ids.

The `@JpaEntityScan` annotation can be used to specify the packages to scan for JPA entity classes mapping, one for the `one` data context id and another for the `two` data context id:

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpringBoot3.java[tag=config,indent=0]
----
<1> Use the base package of the `TestEntity1` class to scan for the JPA entity classes to map to the `EntityManagerFactory` bean associated to the `one` data context id  
<2> Use the base package of the `TestEntity2` class to scan for the JPA entity classes to map to the `EntityManagerFactory` bean associated to the `two` data context id  

[[JPADatastoreSpringBootStarters]]
=== Spring Boot starters

The following _starter_ artifacts are available to provide a quick project configuration setup using Maven dependency system:

*1.* *JPA starter using Hibernate* provides the dependencies to the Holon JPA Spring Boot integration artifact `holon-datastore-jpa-spring-boot` and the dependencies to use *Hibernate ORM* as persistence provider.

Furthermore, it provides dependencies for:

* The link:holon-core.html#SpringBoot[Holon Platform Core Module Spring Boot integration^] base starter (`holon-starter`).
* The base Spring Boot starter (`spring-boot-starter`), see the link:https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-starter[Spring Boot starters documentation^] for details.
* The https://github.com/brettwooldridge/HikariCP[HikariCP] pooling `DataSource` implementation.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jpa</groupId>
<artifactId>holon-starter-jpa-hibernate</artifactId>
<version>{revnumber}</version>
----

*2.* *JPA starter using Eclipselink* provides the same dependencies as the previous JPA starter, but using *Eclipselink* as persistence provider, instead of Hibernate.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jpa</groupId>
<artifactId>holon-starter-jpa-eclipselink</artifactId>
<version>{revnumber}</version>
----
