== Spring framework integration

The `holon-datastore-jpa-spring` artifact provides integration with the https://spring.io[Spring^] framework for the JPA Datastore.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jpa</groupId>
<artifactId>holon-datastore-jpa-spring</artifactId>
<version>{revnumber}</version>
----

[[SpringJpaDatastore]]
=== Datastore setup

To create a JPA Datastore and register it as a Spring bean, the link:{apidir}/com/holonplatform/jpa/spring/SpringJpaDatastore.html[SpringJpaDatastore^] interface is provided, with the convenience `builder()` method.

This interface creates and represents a JPA Datastore implementation which supports Spring JPA and JTA transaction management architecture, using a Spring _transactional EntityManager proxy_ as Datastore `EntityManager`.

[[EnableJpaDatastore]]
=== Datastore auto-configuration

The link:{apidir}/com/holonplatform/datastore/jpa/spring/EnableJpaDatastore.html[EnableJpaDatastore^] 
annotation can be used on Spring configuration classes to enable automatic JPA Datastore configuration. An available `EntityManagerFactory` type bean must be present in context to enable the JPA Datastore.

The _data context id_ to which the JPA Datastore is bound can be configured using the `dataContextId` annotation attribute, useful when multiple JPA persistence units are available and it is required to configure multiple JPA Datastore instances.

When a _data context id_ is not specified, the JPA Datastore is bound to the unique `EntityManagerFactory` type bean registered in context. If the bean is not unique or is not present, a configuration error is thrown. The `entityManagerFactoryReference` annotation attribute can be used to specify the explicit `EntityManagerFactory` bean name to use for the JPA Datastore.

When a _data context id_ is specified, the registered Datastore is bound to the `EntityManagerFactory` with a matching
_data context id_, if available. During registration phase, if a `entityManagerFactoryReference` is not specified, an `EntityManagerFactory` bean is searched in context using the bean name pattern: `entityManagerFactory_[datacontextid]` where `[datacontextid]` is equal to the 
`dataContextId` annotation attribute.

The _auto-flush_ mode can be specified using the `autoFlush` annotation attribute.

The `transactional` annotation attribute (`true` by default) can be used to control the Spring transactions architecture integration, i.e. if a `Transactional` behaviour must be configured for the JPA Datastore data manipulation methods, to automatically create or partecipate in a Spring transaction when these methods are invoked. 

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring.java[tag=spring,indent=0]
----

==== Commodity factories

To use the `DatastoreCommodityFactory` annotation on beans to automatically register them into the `Datastore`, the `JpaDatastoreCommodityFactory` base type must be used for such beans.

See <<CommodityFactories>> for additional details about the `JpaDatastoreCommodityFactory` type.

[[EnableJpa]]
=== Full JPA auto-configuration

The link:{apidir}/com/holonplatform/datastore/jpa/spring/EnableJpa.html[EnableJpa^] 
annotation can be used on Spring configuration classes to setup a full JPA enviroment bean stack: 

* *DataSource:* If a `javax.sql.DataSource` type bean is not already registered in Spring context, a `DataSource` instance is created and configured using standard JDBC `DataSourceConfigProperties`;
* *EntityManagerFactory:* A `javax.persistence.EntityManagerFactory` bean is registered and configured, along with a suitable Spring `JpaVendorAdapter` instance for ORM configuration;
* *PlatformTransactionManager:* A `org.springframework.transaction.PlatformTransactionManager` bean is registered to be used within the Spring transaction infrastructure;
* *Datastore:* A `JpaDatastore` is configured and bound to the `EntityManagerFactory` of the JPA stack.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring.java[tag=jpa,indent=0]
----

==== `EnableJpa`: DataSource configuration

A `DataSource` type bean is automatically configured if:

* A `javax.sql.DataSource` type bean is not already registered in Spring context;
* The `dataSourceReference` attribute of the `EnableJpa` is not specified. If specified, it indicates the `DataSource` bean name to use, which must be available in Spring context.

In order to auto-configure the `DataSource` bean, a suitable set of configuration properties must be available in Spring environment (typically using one or more `PropertySource`).

See link:../../holon-jdbc/overview.html#DataSourceConfigProperties[DataSource configuration properties^] for details.

==== `EnableJpa`: EntityManagerFactory configuration

A Spring `LocalContainerEntityManagerFactoryBean` instance is used as `javax.persistence.EntityManagerFactory` implementation to ensure a full integration with Spring JPA architecture and provide functionalities such as automatic JPA persistence unit configuration without the need of a `persistence.xml` configuration file.

If a `persistence.xml` configuration file is not available, automatic persistence unit _entity_ classes configuration can be performed using either the annotation attribute:

* `entityPackages` : providing a list of package names to scan in order to map JPA _entity_ classes into the  `EntityManagerFactory`,

or the annotation attribute:

* `entityPackageClasses` : providing a list of classes from which to obtain the package names to scan in order to map JPA _entity_ classes into the `EntityManagerFactory`. Represents a type-safe alternative to `entityPackages` attribute.

Two more annotation attributes are available for persistence unit configuration:

* `validationMode` : Specify the JPA 2.0 validation mode for the persistence unit;
* `sharedCacheMode` : Specify the JPA 2.0 shared cache mode for the persistence unit.

See the JPA documentation for further details about persistence unit configuration.

==== `EnableJpa`: Persistence provider (ORM) configuration

The JPA Persistence provider (ORM) to use is auto-detected from classpath and a suitable Spring `JpaVendorAdapter` instance is configured and bound to the `EntityManagerFactory`.

See link:{apidir}/com/holonplatform/datastore/jpa/ORMPlatform.html[ORMPlatform^] enumeration for a list of supported persistence provider implementations.

If more than one persistence provider implementation is present in classpath (or to explicitly specify a persistence provider implementation to use, anyway) the `orm` configuration property can be used. See <<JPA configuration properties>> for details.

==== `EnableJpa`: Transaction manager configuration

A Spring JPA `PlatformTransactionManager` is auto-configured and bound to the 
`EntityManagerFactory` to enable Spring's transaction infrastructure support.

A set of attributes are made available by the `@EnableJpa` annotation to fine tune the transaction manager configuration: `transactionSynchronization`, `defaultTimeout`, `validateExistingTransaction`, `failEarlyOnGlobalRollbackOnly`, `rollbackOnCommitFailure`.

See link:{apidir}/com/holonplatform/datastore/jpa/spring/EnableJpa.html[EnableJpa^] Javadocs for informations about each of these configuration attributes.

==== `EnableJpa`: JPA Datastore configuration

By default, using the `EnableJpa` annotation a JPA Datastore is automatically created and configured suing the `EntityManagerFactory` of the JPA beans stack. The JPA Datastore instanc will be a <<SpringJpaDatastore>>, enabling all the Spring-related auto-configuration features described above.

To disable automatic JPA Datastore configuration, the `enableDatastore` annotation attribute can be used.

The `EnableJpa` annotation makes available two additional configuration attributes related to the JPA Datastore setup:

* `autoFlush` : to enable the JPA Datastore _auto flush_ mode. When auto-flush mode is enabled,
the `EntityManager.flush()` method is invoked after each Datastore data manipulation operation to ensure the underlying database synchronization.

* `transactionalDatastore` : to add _transactional_ behaviour to
suitable Datastore methods, i.e. to automatically create or partecipate in a transaction when methods are invoked.

==== Using _data context id_ for multiple data sources

When a _data context id_ is specified through the `dataContextId` annotation attribute, all the JPA stack beans auto-configured with the `EnableJpa` annotation are bound to the specified _data context id_ name, allowing the support for multiple data sources and persistence units.

When a _data context id_ is specified:

* Any configuration property (for `DataSource` or JPA beans configuration) must be provided using the _data context id_ as prefix. For example, if the _data context id_ is named `test`, the JDBC DataSource url must be specified the following way: `holon.datasource.test.url=...` and so on;

* The _data context id_ will be used as persistence unit name;

* Each of the auto-configured JPA stack bean will be _qualified_ using the _data context id_ name, to allow dependency injection using a Spring `Qualifier`.

In case of multiple data context ids, the `primary()` attribute of the `EnableJpa` annotation can be used to mark one the JPA beans stack as primary candidate for dependency injection when a qualifier is not specified.

[source, java]
----
include::{examplesdir}/com/holonplatform/datastore/jpa/examples/ExampleJpaDatastoreSpring.java[tag=multi,indent=0]
----

[[JPA configuration properties]]
=== JPA configuration properties

link:{apidir}/com/holonplatform/jpa/spring/JpaConfigProperties.html[JpaConfigProperties^] interface provides a set of configuration properties to be used with JPA stack beans auto-configuration. It extends a default `ConfigPropertySet` bound to the property name prefix *holon.jpa*.

The available configuration properties are listed below:

.JPA configuration properties
|===
|Name |Type |Meaning

|_holon.jpa._ *orm*
|link:{apidir}/com/holonplatform/datastore/jpa/ORMPlatform.html[ORMPlatform^] enumeration
|ORM platform to use as persistence provider.

|_holon.jpa._ *dialect*
|String
|ORM dialect class name to use, if supported by the ORM platform.

| _holon.jpa._ *database*
|`com.holonplatform.jdbc.DatabasePlatform` enumeration
|Database platform to which the `DataSource` is connected (auto-detected by default).

|_holon.jpa._ *generate-ddl*
|Boolean (true/false)
|Whether to initialize the database schema on startup.

|_holon.jpa._ *show-sql*
|Boolean (true/false)
|Whether to instruct JPA ORM engine to show executed SQL statements, if supported by ORM platform.
|===

The `JpaConfigProperties` can be loaded from a number a sources using the default `ConfigPropertySet` builder interface.

Using the Spring integration, all `Environment` registered PropertySources will be enabled as a `JpaConfigProperties` source.

== Spring Boot integration

The `holon-datastore-jpa-spring-boot` artifact provides integration with https://projects.spring.io/spring-boot[Spring Boot^] for JPA stack and Datastore auto-configuration.

To enable Spring Boot auto-configuration the following artifact must be included in your project dependencies:

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jpa</groupId>
<artifactId>holon-datastore-jpa-spring-boot</artifactId>
<version>{revnumber}</version>
----

=== JPA Datastore auto-configuration

The JPA datastore is auto-configured only when:

* A `JpaDatastore` type bean is not already registered in Spring context
* A valid `EntityManagerFactory` type bean is available in Spring context

The JPA Datastore auto-configuration behaviour is the same of the one adopted by the `EnableJpaDatastore` annotation. See <<EnableJpaDatastore>> for details.

To disable this auto-configuration feature the `JpaDatastoreAutoConfiguration` class can be excluded:

[source, java]
----
@EnableAutoConfiguration(exclude={JpaDatastoreAutoConfiguration.class})
----

=== Full JPA stack auto-configuration

A full JPA beans stack is auto-configured only when:

* An `EntityManagerFactory` type bean is not already registered in Spring context.

The JPA stack auto-configuration behaviour is the same of the one adopted by the `EnableJpa` annotation. See <<EnableJpa>> for details.

To disable this auto-configuration feature the `JpaAutoConfiguration` class can be excluded:

[source, java]
----
@EnableAutoConfiguration(exclude={JpaAutoConfiguration.class})
----

==== JPA entities scan

When the full JPA stack auto-configuration is enabled, the link:{apidir}/com/holonplatform/jpa/spring/boot/JpaEntityScan.html[JpaEntityScan^] repeatable annotation can be used on Spring configuration classes to specify the base packages to scan for JPA entity classes.

=== Spring Boot starters

The following _starter_ artifacts are available to provide a quick project configuration setup using Maven dependency system:

*1.* *JPA Datastore starter using Hibernate* provides the dependencies to the Holon JPA Datastore Spring Boot integration artifacts, in addition to default Holon _core_ Spring Boot starters (see the documentation for further information) and base Spring Boot starter (`spring-boot-starter`). Futhermore, this starter provides the *Hibernate ORM* and the *HikariCP* DataSource dependencies.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jpa</groupId>
<artifactId>holon-starter-jpa-hibernate</artifactId>
<version>{revnumber}</version>
----

*2.* *JPA Datastore starter using Eclipselink* provides the dependencies to the Holon JPA Datastore Spring Boot integration artifacts, in addition to default Holon _core_ Spring Boot starters (see the documentation for further information) and base Spring Boot starter (`spring-boot-starter`). Futhermore, this starter provides the *Eclipselink ORM* and the *HikariCP* DataSource dependencies.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jpa</groupId>
<artifactId>holon-starter-jpa-eclipselink</artifactId>
<version>{revnumber}</version>
----
