= Holon JPA Datastore
:revnumber: {project-version}
:apidir: ../api/holon-datastore-jpa
:linkattrs:
:sectnums:
:nofooter:
:toc: left
:toclevels: 3

Copyright © 2016-2017

_Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically._

== Introduction

The Holon *JPA Datastore* is the _Java Persistence API_ reference implementation of the link:../../api/holon-core/com/holonplatform/core/datastore/Datastore.html[Datastore^] abstraction. 

TIP: See the link:../../holon-core/core.html#Datastore[Datastore] documentation for further informations about Datastores.

This `Datastore` uses the JPA link:https://docs.oracle.com/javaee/7/api/javax/persistence/EntityManagerFactory.html[EntityManagerFactory] interface as a factory to obtain link:https://docs.oracle.com/javaee/7/api/javax/persistence/EntityManager.html[EntityManager] instances, used by the `Datastore` to perform persistence operations and queries through the `JPQL` language.

IMPORTANT: The Holon Platform JPA modules and components require *JPA 2.0 or higher*, so a JPA 2.0/2.1 compliant persistence provider is needed at runtime.

The `holon-datastore-jpa` artifact is the main entry point to use the JPA Datastore.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jpa</groupId>
<artifactId>holon-datastore-jpa</artifactId>
<version>{revnumber}</version>
----

NOTE: To use a JPA Datastore, an link:https://docs.oracle.com/javaee/7/api/javax/persistence/EntityManagerFactory.html[EntityManagerFactory] instance must be configured and available. `EntityManagerFactory` setup (including any ORM platform configuration concerns) is beyond the scope of this documentation.

include::_datastore.adoc[]

include::_spring.adoc[]

== Maven BOM

A Maven _Bill of materials_ (BOM) artifact which provides all available dependencies for the JPA Datastore module is available:

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jpa</groupId>
<artifactId>holon-datastore-jpa-bom</artifactId>
<version>{revnumber}</version>
----

== Loggers

By default, the Holon platform uses the https://www.slf4j.org[SLF4J^] API for logging. The use of SLF4J is optional: it is enabled when the presence of SLF4J is detected in the classpath. Otherwise, logging will fall back to JUL (`java.util.logging`).

The logger name for the *JPA Datastore* module is `com.holonplatform.datastore.jpa`.

== System requirements

=== Java

The Holon Platform JPA Datastore module requires https://www.java.com[Java] *8* or higher.

=== JPA

The *Java Persistence API version 2.0 or higher* is required for the JPA Datastore module proper use. To use most recent JPA features, such as _left joins_ and the _ON_ clause, the *Java Persistence API version 2.1* is required.

=== Persistence providers

Altough any JPA 2.0 or higher compliant persistence provider (ORM) is supported, the Holon Platform JPA Datastore module is tested and certified with the followings:

* http://hibernate.org/orm[Hibernate ORM] version *4.x* or *5.x*
* http://www.eclipse.org/eclipselink[EclipseLink] version *2.5 or higher*

